# -*- coding: utf-8 -*-
"""credit_scoring.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bTwyONF96ft_8jpkMd7tOwNEpyjUv7-
"""

# Credit Scoring Model using Logistic Regression
# Corrected code for Google Colab: Downloads the German Credit dataset, handles categorical features, and avoids errors.

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# Download and load the German Credit dataset (public dataset from UCI)
# This dataset has no headers, so we add column names manually.
# Target: 'Creditworthy' (1 = Good credit, 2 = Bad credit; we'll recode to 0/1 for binary classification)
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data"
column_names = [
    'Status_of_existing_checking_account', 'Duration_in_month', 'Credit_history', 'Purpose',
    'Credit_amount', 'Savings_account/bonds', 'Present_employment_since',
    'Installment_rate_in_percentage_of_disposable_income', 'Personal_status_and_sex',
    'Other_debtors/guarantors', 'Present_residence_since', 'Property', 'Age_in_years',
    'Other_installment_plans', 'Housing', 'Number_of_existing_credits_at_this_bank',
    'Job', 'Number_of_people_being_liable_to_provide_maintenance_for', 'Telephone',
    'Foreign_worker', 'Creditworthy'
]
data = pd.read_csv(url, sep=' ', header=None, names=column_names)

# Recode target: 1 (Good) -> 1, 2 (Bad) -> 0 for binary classification
data['Creditworthy'] = data['Creditworthy'].map({1: 1, 2: 0})

# Handle categorical features: Encode string columns to numbers using LabelEncoder
# (This is a simple approach; for better results, you could use OneHotEncoder)
categorical_columns = [
    'Status_of_existing_checking_account', 'Credit_history', 'Purpose', 'Savings_account/bonds',
    'Present_employment_since', 'Personal_status_and_sex', 'Other_debtors/guarantors',
    'Property', 'Other_installment_plans', 'Housing', 'Job', 'Telephone', 'Foreign_worker'
]
le = LabelEncoder()
for col in categorical_columns:
    data[col] = le.fit_transform(data[col])

# Check the data (optional: uncomment to see first few rows after encoding)
# print(data.head())

# Split features and target
X = data.drop("Creditworthy", axis=1)
y = data["Creditworthy"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = LogisticRegression(max_iter=1000, random_state=42)  # Added random_state for reproducibility
model.fit(X_train, y_train)

# Predict
predictions = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, predictions)
print("Model Accuracy:", accuracy)

# Detailed report
print(classification_report(y_test, predictions))